# Generated by Django 5.0.6 on 2024-05-30 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_book_description_alter_member_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='member',
        ),
        migrations.RemoveField(
            model_name='order',
            name='books',
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
