# Generated by Django 5.0.6 on 2024-05-30 04:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_borroed_books_member_borrowed_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.IntegerField(choices=[(1, 'Regular Member'), (2, 'Premium Member'), (3, 'Guest Member')], default=1),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.IntegerField(choices=[(0, 'Purchase'), (1, 'Borrow')], default=1)),
                ('date', models.DateField(default=datetime.datetime(2024, 5, 30, 4, 2, 54, 502454, tzinfo=datetime.timezone.utc))),
                ('books', models.ManyToManyField(blank=True, to='myapp.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.member')),
            ],
        ),
    ]
