# Generated by Django 5.0.6 on 2024-05-30 05:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_book_description_publisher_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_renewal',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
